
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS queryLevel;
CREATE TABLE IF NOT EXISTS queryLevel(
	id INT PRIMARY KEY AUTO_INCREMENT,
	levelName VARCHAR(20)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;