
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS staff;
CREATE TABLE staff(
	`staffId` INT PRIMARY KEY AUTO_INCREMENT,
	`username` VARCHAR(10) NOT NULL unique,
	`password` VARCHAR(10) NOT NULL,
	`staffQl_id` INT,
	FOREIGN KEY(staffQl_id) REFERENCES queryLevel(id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;